language: cpp
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cmake .
- cmake --build .
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T homework_0-1.2.3-Linux.deb -ualexscherba16:$BINTRAY_API_KEY "https://api.bintray.com/content/alexscherba16/otus-cpp/homework_0/$TRAVIS_BUILD_NUMBER/homework_0-1.2.3-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

